name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "hiokjb.py" | docker login -u "kishoredk" --password-stdin

    - name: Build the Docker image
      run: |
        IMAGE_TAG=dk:$(date +%s)
        docker build . --file Dockerfile --tag kishoredk/test:$IMAGE_TAG
        docker push kishoredk/test:$IMAGE_TAG
